name: jupyterlab-itables-dev
channels:
  - defaults
dependencies:
  - python>=3.7
  - jupyterlab>=3.3
  - nodejs
  - nb_conda_kernels
  - requests
  - pip
  - twine
  - pip:
    - jupyter-packaging>=0.12
